### ISSUE TITLE
StmInfo Error 404.

### ISSUE THREAD

**Issue by jisamcom** [Slyyxp/GeniePy#1]
command
python genie.py -u https://www.genie.co.kr/detail/albumInfo?axnm=81125363

URL : 
https://www.genie.co.kr/detail/albumInfo?axnm=81125363

 _______               __         ______
|     __|.-----.-----.|__|.-----.|   __ \.--.--.
|    |  ||  -__|     ||  ||  -__||    __/|  |  |
|_______||_____|__|__||__||_____||___|   |___  |
                                         |_____|

requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): app.genie.co.kr
Client      : INFO     Login Successful.
Genie       : INFO     Album 1 of 1
Genie       : INFO     Album found: 드렁큰 타이거 - Drunken Tiger X : Rebirth Of Tiger JK
Utilities   : INFO     cover.jpg already exists locally.
requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): stm.genie.co.kr
Traceback (most recent call last):
  File "genie2.py", line 166, in <module>
    main()
  File "genie2.py", line 122, in main
    s_meta = client.get_stream_meta(track['SONG_ID'], args.f)
  File "E:\git\GeniePy\modules\client.py", line 101, in get_stream_meta
    r = self.make_call("stm", "player/j_StmInfo.json", data)
  File "E:\git\GeniePy\modules\client.py", line 38, in make_call
    r.raise_for_status()
  File "C:\Python38\lib\site-packages\requests\models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://stm.genie.co.kr/player/j_StmInfo.json

**Comment by Slyyxp** [comment]
I'm actually not sure at all on why this particular track responds with a 404.

For now I've caught the exception and continue'd until I can find the reason for the response.
https://github.com/Slyyxp/GeniePy/commit/f666ed5f5ea6d48c0681f8d87ff9afe55dfff3fd

**Comment by idfrann0** [comment]
Traceback (most recent call last):
  File "genie.py", line 169, in <module>
    client.auth()
  File "C:\GeniePy-master\modules\client.py", line 52, in auth
    raise exceptions.AuthenticationError("Authentication failed.")
modules.exceptions.AuthenticationError: Authentication failed.

why ? Im loggin via kakao

**Comment by Slyyxp** [comment]
> Traceback (most recent call last): File "genie.py", line 169, in client.auth() File "C:\GeniePy-master\modules\client.py", line 52, in auth raise exceptions.AuthenticationError("Authentication failed.") modules.exceptions.AuthenticationError: Authentication failed.
> 
> why ? Im loggin via kakao

Unrelated to this issue, has been moved.
