### ISSUE TITLE
All releases downloaded in MP3.

### ISSUE THREAD

**Issue by idfrann0** [Slyyxp/GeniePy#4]
I have a subscription but everything is downloaded in mp3 :/

**Comment by Slyyxp** [comment]
More information is required, what is your subscription type? It is possible your subscription only allows the download of MP3's.

**Comment by idfrann0** [comment]
I bought a pass, but I want a subscription to flac music, but apparently nobody knows how to do it. Apparently I think you can only use KT + to buy a pass in flac format.

**Comment by Slyyxp** [comment]
Closed.
Reason for error: User does not meet subscription requirement.
