### ISSUE TITLE
python error: "KeyError: 'TPOS'"

### ISSUE THREAD

**Issue by awsms** [Slyyxp/GeniePy#5]
> Traceback (most recent call last):

> File "/home/user/Nameless/GeniePy/genie.py", line 172, in

> main()

> File "/home/user/Nameless/GeniePy/genie.py", line 150, in main

> raise e

> File "/home/user/Nameless/GeniePy/genie.py", line 147, in main

> fix_tags(pre_abs, ext, f_meta)

> File "/home/user/Nameless/GeniePy/genie.py", line 65, in fix_tags

> audio['TPOS'] = id3.TPOS(text=str(audio['TPOS']) + "/" + str(f_meta['disc_total']))

> File "/home/user/.pyenv/versions/3.9.0/lib/python3.9/site-packages/mutagen/_util.py", line 537, in __getitem__

> return self.__dict[key]

> KeyError: 'TPOS'

Had this issue when trying to download https://www.genie.co.kr/detail/albumInfo?axnm=59676086

**Comment by Slyyxp** [comment]
Resolved with latest commit https://github.com/Slyyxp/GeniePy/commit/3580cad5e2bca455c92c8cfd513fb5f6df9bc818
